export const PERSON_USER='PERSON_USER'
export const PERSON_MANAGER='PERSON_MANAGER'
export const PERSON_TEACHER='PERSON_TEACHER'
export const PERSON_ADMIN='PERSON_ADMIN'
export const OUT_TO_LIGIN='OUT_TO_LIGIN'

